# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BPSwoc',
                'doc_host': 'https://josephrilling.github.io',
                'git_url': 'https://github.com/josephrilling/BPSwoc',
                'lib_path': 'BPSwoc'},
  'syms': {'BPSwoc.core': {'BPSwoc.core.foo': ('core.html#foo', 'BPSwoc/core.py')}}}
