# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BPSwoc',
                'doc_host': 'https://josephrilling.github.io',
                'git_url': 'https://github.com/josephrilling/BPSwoc',
                'lib_path': 'BPSwoc'},
  'syms': { 'BPSwoc.bps': { 'BPSwoc.bps.BPS': ('bps.html#bps', 'BPSwoc/bps.py'),
                            'BPSwoc.bps.BPS.__init__': ('bps.html#bps.__init__', 'BPSwoc/bps.py'),
                            'BPSwoc.bps.BPS.fit': ('bps.html#bps.fit', 'BPSwoc/bps.py'),
                            'BPSwoc.bps.BPS.predict': ('bps.html#bps.predict', 'BPSwoc/bps.py')}}}
